# https://github.com/d-kuro/gwq?tab=readme-ov-file#configuration
[worktree]
basedir = "~/git"
auto_mkdir = true

[finder]
preview = true

[naming]
template = "{{.Host}}/{{.Owner}}/{{.Repository}}={{.Branch}}" # Keep worktrees separate from ghq-cloned repos.
sanitize_chars = { "/" = "-", ":" = "-" }

[ui]
icons = true
tilde_home = true
